<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115072406 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lending (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, returned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_copy_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_74AB8C033B550FE4 ON lending (book_copy_id)');
        $this->addSql('CREATE INDEX IDX_74AB8C03A76ED395 ON lending (user_id)');
        $this->addSql('ALTER TABLE lending ADD CONSTRAINT FK_74AB8C033B550FE4 FOREIGN KEY (book_copy_id) REFERENCES book_copy (id)');
        $this->addSql('ALTER TABLE lending ADD CONSTRAINT FK_74AB8C03A76ED395 FOREIGN KEY (user_id) REFERENCES bot_user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lending DROP CONSTRAINT FK_74AB8C033B550FE4');
        $this->addSql('ALTER TABLE lending DROP CONSTRAINT FK_74AB8C03A76ED395');
        $this->addSql('DROP TABLE lending');
    }
}
